### PR TITLE
Implement RE2 fill video double buffer ucode

### PR DESCRIPTION
**Pull request by Gillou68310**

### CODE REVIEW

**Comment by bsmiles32** [comment]
Congratulations ! This is excellent work. Now I guess you can enjoy playing RE2 on your phone ;)

**Comment by Gillou68310** [comment]
Well this one was easy it's just a color average between 2 video frames. I'm not playing on my phone so much but at least re2 has no more secrets :-)

**Comment by bsmiles32** [comment]
Quick question, I saw you used floating point to do the average computation, is that required or simply using integer arithmetic would have sufficed ?

**Comment by bsmiles32** [comment]
Since you sum 2 integers in the 0-255 range, then divide by 2, you need at most 9 bits for the intermediate summation, so using integers should be sufficient. Or am I missing something ?

**Comment by Gillou68310** [comment]
You're right using integers will definitely produce the same value. I tried to mimic what the assembly code do but I didn't notice that the only reason why they are using real is to make use of vectors and process 2 pixels at a time.

**Comment by Gillou68310** [comment]
I pushed the change directly on master

**Comment by Gillou68310** [comment]
Thanks for reviewing ;-)

**Pull request merged**
