### PR TITLE
Implement HVQM ucode

### PR DESCRIPTION
**Pull request by Gillou68310**
Here's my RE notes:
[hvqm2sp1.txt](https://github.com/mupen64plus/mupen64plus-rsp-hle/files/4149303/hvqm2sp1.txt)

### CODE REVIEW

**Comment by Narann** [comment]
Code is nice! Anyone want to test before merging? @loganmc10 @bsmiles32 ?

**Comment by Gillou68310** [comment]
I tested both pokemon puzzle and Yakouchuu II, but it's definitely worth double checking before merging

**Comment by bsmiles32** [comment]
I tested both Yakouchuu and Pokemon Puzzle league and saw no obvious mistakes.

**Comment by Gillou68310** [comment]
thanks @bsmiles32, I merged your suggestions and squashed everything

**Comment by loganmc10** [comment]
I tried out Pokemon Puzzle League and it looks great, good work @Gillou68310 !

**Comment by Gillou68310** [comment]
thanks for testing ;-)

**Comment by Narann** [comment]
And here we are! Thanks all for fast feedback!

If I'm not mistaking, it was the last missing RSP HLE implementation of N64 ucode, so amazing job all!

**Comment by fzurita** [comment]
So we no longer need a fallback RSP? That's nice!

**Pull request merged**
